### PR TITLE
Don't hardcode sizeof GLfloat

### PR DESCRIPTION
**Pull request by Lonami**
https://stackoverflow.com/a/27214322/4759433

### CODE REVIEW

**Comment by Lonami** [comment]
(Some day, GitHub will allow me to edit several files before making a single commit. Until that day comes, every file is a different commit. Feel free to squash them).

**Comment by tartley** [comment]
Brilliant! Thanks. You rock. I couldn't figure that out.

**Comment by Lonami** [comment]
I tested this on Python 3.x, not 2.7 though! Hopefully it works the same.

**Comment by tartley** [comment]
Is OK. I didn't even try it out before merging - as you can see, this repo is old and abandoned long ago. I fired it up just now, and had a few problems:
1. I had to tweak your use of GLfloat a bit, it didn't quite match up with the imports.
2. i did some other minor tidying
3. Once I got it running, I only saw a black window. No idea what my problem is.

You can see my fixes  (1) and (2) on master now.

**Comment by Lonami** [comment]
I also tried running the examples under Python 3, but got a few other issues. Ah well, it still serves well to showcase how to call PyOpenGL methods :)

**Comment by tartley** [comment]
Yeah, me too. Thanks for the good, very much appreciated. I learned something that I'll use elsewhere...

**Pull request merged**
